### ISSUE TITLE
markdown copy injects escape characters that are interpreted literally in Slack (and probably other apps)

### ISSUE THREAD

**Issue by YAMLcase** [hansifer/tab-copy#11]
For tab titles with square brackets, it appears Tab Copy is injecting escape characters to deal with nested brackets.  Unfortunately backslashes are interpreted literally in Slack and break the formatting (example below).  

This behavior is new since the big overhaul of Tab Copy that was recently released so hopefully it's an easily identifiable bug that can be fixed.  If not, here are some options I'd be happy with:
- replace square brackets with parenthesis.  example: `[foo] bar` becomes `(foo) bar` 
- remove the brackets if start or end, otherwise replace with a suitable delimiter character like `-`, `:`, etc.  example: `[foo] bar` becomes `foo: bar` or `foo - bar`

Copied using "Markdown" format from Tab Copy:
```
[\[PROJECT-123\] This is a test project - Jira](https://jira.mycompany.com/browse/PROJECT-123)
```

What slack shows:
![image](https://github.com/user-attachments/assets/d4653ec1-0383-40fb-9c26-fe2665f9e3bd)

**Comment by hansifer** [comment]
This is a fix in v4. Failing to [escape](https://daringfireball.net/projects/markdown/syntax#backslash) was a bug. In fact, we still don't escape aggressively enough.

This is also indicative of a bug in Slack's handling of escaped Markdown links. It seems less than ideal to add logic to accommodate bugs, limitations, or non-standard behavior in 3rd party apps.

You could disable markup in Slack and use the `Link` format, although I'm sure you have your reasons for enabling it.

FWIW, there's two features on the [roadmap](https://tabcopy.com/roadmap) that could the used to address this:

- **Rewrite rules**: adds ability to define rules for modifying tab titles, URLs, or icons in-flight when copying
- **Enhanced custom formats**: includes addition of conditionals and functions (eg, `replace()`)
