### ISSUE TITLE
Number of tabs in current windows / all windows

### ISSUE THREAD

**Issue by Shassk** [hansifer/tab-copy#12]
Hi. So why in the latest version it stopped showing the number of tabs? It was massively useful when all your tabs don't fit on the screen, and the number would tell whether you're 1-2 or 100+ tabs over the threshold. Now it's all gone. Can you bring it back? I've used it way more often than I was switching between output formats for example.

**Comment by hansifer** [comment]
It's planned: [Feature roadmap | Tab Copy](https://tabcopy.com/roadmap#option-to-show-tab-count-badges-on-copy-buttons)

**Comment by hansifer** [comment]
For anyone who would like to pick this up, drop a comment here first to prevent potential duplication of effort. 

The way I'm thinking of doing this is with a right-aligned circular badge on each copy button. Let me know if you have other thoughts on this or anything below.

- "This tab" only shows the badge when multiple tabs are selected
- "All windows and tabs" should show both window and tab counts... so the badge would be something like "3 / 21". Not sure how awkward that is though. Open to other ideas.
- requires reactivity to recalculate counts based on:
  - window or tab open/close, tab pin/unpin, highlight, move, etc
    - take tab filtering into consideration for all scopes except `highlighted-tabs`
  - options changes
    - specifically "Ignore pinned tabs" but probably best to future proof by listening to any
    - use `makeStorageChangeHandler`
- if we're calculating counts, we can also disable buttons with 0 count
  - include a tooltip to explain the button state

**Comment by Shassk** [comment]
> * "All windows and tabs" should show both window and tab counts... so the badge would be something like "3 / 21". Not sure how awkward that is though. Open to other ideas.

Keep it integrated kinda like it was before?
![image](https://github.com/user-attachments/assets/c185be1d-0427-49aa-bde3-c8e900c85568)
Maybe something like "All 3 windows and 21 tabs"?

**Comment by hansifer** [comment]
> Maybe something like "All 3 windows and 21 tabs"?

Possibly. The benefits of badges would be that they read somewhat easier, keep labels consistent, and simplify intl.

**Comment by hansifer** [comment]
This is now in progress. Here's a preview:

![tab-copy-tab-counts-preview](https://github.com/user-attachments/assets/49e82ba2-8a11-4954-8d6b-7baf78a5688a)

For "All windows and tabs" I'm thinking possibly providing an option to show tab counts vs window counts.

**Comment by hansifer** [comment]
This has been released.

[v4.1.0](https://tabcopy.com/releases/4-1-0)
