### ISSUE TITLE
why mac Option+C can not setting as a shortcut

### ISSUE THREAD

**Issue by xunwumizhi** [hansifer/tab-copy#13]
<img width="679" alt="image" src="https://github.com/user-attachments/assets/063121e0-251f-40a3-a8a7-2dfaacd1dc16">

I  have to change another shortcut, like Option+X

**Comment by hansifer** [comment]
`Option+c` works fine as a Tab Copy shortcut.

If you're not able to set a shortcut, it's usually because another extension is already using it.
