### ISSUE TITLE
Keyboard shortcut for second format

### ISSUE THREAD

**Issue by mfulton26** [hansifer/tab-copy#6]
I use this extension a lot, mainly to grab formatted links to put in emails and other messages but occasionally I need it in Markdown format instead. I mostly use a keyboard shortcut for getting the formatted link but in order to get it in my second format I have to use the context menu, etc. It would be great if I could bind the 2nd format to a keyboard shortcut too (e.g. Shift+Option+C on my macOS to accompany Option+C which I use for the first format). Thank you.

**Comment by hansifer** [comment]
As of v4, the most streamlined way to apply alternative formats is as follows:

# Setup

- Bind the "Activate the extension" keyboard shortcut (go to Tab Copy Options, then click "Edit keyboard shortcuts...")
- Drag formats up or down on the Tab Copy Options page to change their order. Move your 3 most used formats to the top.

# Usage

- Use the new shortcut to open the popup
- In the popup, use `Tab` or arrow `Up`/`Down` to select the desired tab scope and hit `Enter` to copy using the default (ie, topmost) format
  - To use the _second_ format, hold down `Ctrl` or `Cmd` when copying
  - To use the _third_ format, hold down `Shift + Ctrl` or `Shift + Cmd` when copying
