### ISSUE TITLE
Customize plain-text separate from html

### ISSUE THREAD

**Issue by mfulton26** [hansifer/tab-copy#7]
I love the "Link" format… well, except for when I'm pasting to somewhere that doesn't support rich text. Is there a way to make "Link" fallback to "Markdown" for plain text?

e.g.

instead of

```
public.html:<meta charset='utf-8'><a href="https://www.google.com/">Google</a>
public.utf8-plain-text:Google
```

I want

```
public.html:<meta charset='utf-8'><a href="https://www.google.com/">Google</a>
public.utf8-plain-text:[Google](https://www.google.com/)
```

that when we I paste into apps like Notion, GitHub, etc. that support Markdown it will get linkified, etc.

thanks!

**Comment by hansifer** [comment]
FWIW, this is now possible in v4. The Link format has an option to select the plaintext fallback (URL by default as of v4).
